apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iam-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 96.126.106.29.nip.io
    secretName: iam-tls-secret
  rules:
  - host: 96.126.106.29.nip.io
    http:
      paths:
      - path: /iam(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: server-service
            port:
              number: 3000